name: Game build

on:
  pull_request:
    paths:
      - "Bubelinez/**"
      - "Bubelinez.Tests/**"
  push:
    paths:
      - "Bubelinez/**"
      - "Bubelinez.Tests/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build game
        run: docker build -t game .
